// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	// Code Optional machine-readable error code.
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

// Key Base64-encoded key bytes; clients choose URL-safe encoding when embedded in paths.
type Key = string

// KeyValue defines model for KeyValue.
type KeyValue struct {
	// Key Base64-encoded key bytes; clients choose URL-safe encoding when embedded in paths.
	Key Key `json:"key"`

	// Value Base64-encoded value bytes.
	Value Value `json:"value"`
}

// Value Base64-encoded value bytes.
type Value = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// ScanRangeParams defines parameters for ScanRange.
type ScanRangeParams struct {
	// FromKey Inclusive lower bound (base64-encoded key bytes).
	FromKey Key `form:"fromKey" json:"fromKey"`

	// EndKey Exclusive upper bound (base64-encoded key bytes).
	EndKey Key `form:"endKey" json:"endKey"`
}

// PutKeyJSONBody defines parameters for PutKey.
type PutKeyJSONBody struct {
	// Value Base64-encoded value bytes.
	Value Value `json:"value"`
}

// PutKeyJSONRequestBody defines body for PutKey for application/json ContentType.
type PutKeyJSONRequestBody PutKeyJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Range scan
	// (GET /v1/kv)
	ScanRange(w http.ResponseWriter, r *http.Request, params ScanRangeParams)
	// Delete a key (tombstone)
	// (DELETE /v1/kv/{key})
	DeleteKey(w http.ResponseWriter, r *http.Request, key Key)
	// Read a single key
	// (GET /v1/kv/{key})
	GetKey(w http.ResponseWriter, r *http.Request, key Key)
	// Create or update a value
	// (PUT /v1/kv/{key})
	PutKey(w http.ResponseWriter, r *http.Request, key Key)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Range scan
// (GET /v1/kv)
func (_ Unimplemented) ScanRange(w http.ResponseWriter, r *http.Request, params ScanRangeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a key (tombstone)
// (DELETE /v1/kv/{key})
func (_ Unimplemented) DeleteKey(w http.ResponseWriter, r *http.Request, key Key) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read a single key
// (GET /v1/kv/{key})
func (_ Unimplemented) GetKey(w http.ResponseWriter, r *http.Request, key Key) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update a value
// (PUT /v1/kv/{key})
func (_ Unimplemented) PutKey(w http.ResponseWriter, r *http.Request, key Key) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ScanRange operation middleware
func (siw *ServerInterfaceWrapper) ScanRange(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ScanRangeParams

	// ------------- Required query parameter "fromKey" -------------

	if paramValue := r.URL.Query().Get("fromKey"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "fromKey"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "fromKey", r.URL.Query(), &params.FromKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fromKey", Err: err})
		return
	}

	// ------------- Required query parameter "endKey" -------------

	if paramValue := r.URL.Query().Get("endKey"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endKey"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "endKey", r.URL.Query(), &params.EndKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endKey", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScanRange(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "key" -------------
	var key Key

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteKey(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetKey operation middleware
func (siw *ServerInterfaceWrapper) GetKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "key" -------------
	var key Key

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetKey(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutKey operation middleware
func (siw *ServerInterfaceWrapper) PutKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "key" -------------
	var key Key

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutKey(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/kv", wrapper.ScanRange)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/kv/{key}", wrapper.DeleteKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/kv/{key}", wrapper.GetKey)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/kv/{key}", wrapper.PutKey)
	})

	return r
}
